### ISSUE TITLE
Please support a running WASM version for testing

### ISSUE THREAD

**Issue by DerKarlos** [MartinZikmund/messages-multiplatform-uno-sample#1]
I am surprised: The Apple message API is realy open to other operating systems and even for the Web? (May be you could mention in the readme, it is a messenger (specific) for Apple messages.) The WebAssembly version will run on any other OS, will it? Could you support a running WASM version to test your solution?

**Comment by MartinZikmund** [comment]
Hey, as a clarification, this is just a design sample, so it does not provide actual functionality. However, it could be extended and built upon to create such app :-) .
